### ISSUE TITLE
grid rapyd properties not working (orderBy, paginate)

### ISSUE THREAD

**Issue by kitsunekyo** [serverfireteam/panel#297]
using those lines like in the documentation doesnt change anything:
```
$this->grid->orderBy('name','desc');
$this->grid->paginate(100);
```

this should actually order the grid by name (descending) by default. but does nothing. same for paginate.

**Comment by serverfire** [comment]
please do a composer update and let me know if you still have problem

**Comment by kitsunekyo** [comment]
i did an update (updated from 1.5.0 to 1.5.2) and now none of the CRUD views are working.

/panel/Permission/all (and other) just display the filter, export and import buttons and thats it. no error.

this is the all method of my PermissionController:
```
public function all($entity) {

		parent::all($entity);

		$this->filter = \DataFilter::source(new Permission());
		$this->filter->add('id', 'ID', 'text');
		$this->filter->add('name', 'Name', 'text');
		$this->filter->submit('search');
		$this->filter->reset('reset');
		$this->filter->build();

		$this->grid = \DataGrid::source($this->filter);
		$this->grid->add('id', 'ID', true)->style("width:100px");
		$this->grid->add('name', 'Url')->style('width:100px');
		$this->grid->add('label', 'Description');

		$this->addStylesToGrid();

		return $this->returnView();
	}
```

**Comment by serverfire** [comment]
new version released , do a composer update , that bug is fixed

**Comment by kitsunekyo** [comment]
i could now update and it works like a charm. thank you.

the orderBy issues was not solved though. it was caused by myself in the end.

`$this->addStylesToGrid();` 
was called after
```
$this->grid->orderBy('label','desc');
$this->grid->paginate(100);
```

i checked what addStylesToGrid() actually does and turns out it overrides exactly those two settings. 
it would be great if we could add a small line describing what this function does here:
http://laravelpanel.com/docs/master/crud-fields

as it's not part of rapyd but actually the CrudController of the panel.

Thank you for helping me debug this.
